kit-item-behavior-default: OVERRIDE

messages:
  kit-not-found: "&cThe kit &7%kit%&c don't exists!"
  no-permission: "&cYou don't have the permission to use &7%kit%"
  kit-given: "&bYou have received &7%kit%&b!"
  kit-saved: "&bYou have saved &7%kit%%b!"
  cooldown: "&bYou still have to wait a bit to get &7%kit%&b!"

command:
  default: message # or gui

kits-message:
  - "&bKits available &a%ek_availablekits%, &c%ek_unavailablekits%" #papi support here!

cooldowns:
  permissionbased:
    gladiator:
      hello.cooldown: 3600 # in seconds
      hello2.cooldown: 3000 # in seconds
      default: 10 # without this, you're gonna have problems bud
  global:
    gladiator: 3600 # in seconds

kits:
  gladiator:
    permission:
      enabled: true
      value: "enancedkits.kits.gladiator"
    cooldown: "permissionbased" # or global
    showInGui: true
    items:
